all:
	mpic++ -o2 -o main main.cpp lin.cpp system.cpp energy/haroscjastrow.cpp energy/harosc.cpp energy/kinetic.cpp readfile/read_input.cpp setstate/initstate.cpp setstate/unirand.cpp wavefunc/wavefunc.cpp wavefunc/gauss.cpp wavefunc/gaussjastrow.cpp sampler.cpp montec/montec.cpp montec/metrop.cpp montec/hastings.cpp -std=c++11
